### ISSUE TITLE
Fix the problem "RTCDataChannel queue is full" when sending large files

### ISSUE THREAD

**Issue by nidhal-labidi** [compose-us/flottform#21]
Main points that helped to solve this problem: 
* Each time we call `datachannel.send(chunk)` that chunk is added into a buffer.
* `datachannel.bufferedAmount` returns the size of the chunks inside the buffer at a given point in time.
* `datachannel.bufferedAmountLowThreshold` can be set to any value and represents a threshold below which the buffer is considered free / available and above it we risk having the error message "RTCDataChannel queue is full" so we should PAUSE sending chunks when we reach that level.
* The event `bufferedamountlow` will fire whenver `bufferedAmount<bufferedAmountLowThreshold`. We use this event to resume sending the packets one more time.

The code for now works fine. The problem is that it's a bit slow (Tested it with sending 2 videos. 600MB approx took 5-10 minutes to be sent) -> Potential fixes: Increase the size of the chunk being sent (currently it's 16KB) or increase the bufferedAmountLowThreshold (currently it's 128KB) or both.

Note: Links for the variables/event above: 
+ send() : https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/send
+ bufferedamountlow event: https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/bufferedamountlow_event
+ bufferedAmountLowThreshold property: https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/bufferedAmountLowThreshold
+ bufferedAmount property: https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/bufferedAmount

The previous error that we had is the following 

![Image](https://github.com/user-attachments/assets/055c5bc7-ab45-4487-b5ee-a98a62e9a88b)

**Comment by TamaraBogantseva** [comment]
It should be working for now. We need to end e2e test for it
